name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        working-directory: ./app

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 17.x
          cache: "yarn"
          cache-dependency-path: ./app/yarn.lock
      - run: yarn install --frozen-lockfile
      - run: yarn run dist
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          prerelease: false
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: |
            readme.md
            license.md
            build/*.exe
            build/*.blockmap
            build/latest.yml
